apiVersion: v1
kind: Service
metadata:
  name: poc-service

spec:
  selector:
    app: poc-kubernetes

  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}

  type: ClusterIP