apiVersion: v1
kind: Service
metadata:
  name: poc-service

spec:
  selector:
    app: poc-kubernetes

  ports:
    - name: http
      port: { { .Values.app.service.port } }
      targetPort: 8080

  type: ClusterIP