apiVersion: v1
kind: ConfigMap
metadata:
  name: poc-config

data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/{{ .Values.postgres.database }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: update