apiVersion: v1
kind: Secret
metadata:
  name: poc-secret

type: Opaque

stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgres.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.password | quote }}