app:
  replicaCount: 2

  image:
    tag: "4.1"

postgres:
  storage:
    size: 1Gi

ingress:
  enabled: true
  host: poc.local

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

monitoring:
  enabled: true