app:
  replicaCount: 2
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

postgres:
  storage:
    size: 1Gi

ingress:
  enabled: true
  host: poc-prod.local

autoscaling:
  enabled: false