name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Maven build
        run: mvn clean package

      - name: Docker build
        run: docker build -t poc-kubernetes:${{ github.sha }} .